---
# tasks file for BasicConfig_Cobbler

- name: Installing Cobbler packages
  yum:
    name: "{{ item }}"
    state: installed
  with_items: 
    - "{{ BasicConfig_Cobbler_packages }}"

- name: Template Cobbler configuration
  template:
    src: "cobbler_settings.j2"
    dest: "/etc/cobbler/settings"
    owner: root
    group: root
    mode: "0644"

- name: Template Cobbler DHCP configuration
  template:
    src: "{{ BasicConfig_Cobbler_dhcp_template }}"
    dest: "/etc/cobbler/dhcp.template"
    owner: root
    group: root
    mode: "0644"

- name: Syncronize services from templates
  command: cobbler sync

- name: Start services
  service: 
    name: "{{ item }}"
    state: restarted
    enabled: yes
  with_items:
    - httpd
    - dhcpd
    - cobblerd

- name: Initialize cobbler bootloaders
  command: cobbler get-loaders

- name: Install cobbler-web user
  template:
    src: "user.digest.j2"
    dest: /etc/cobbler/users.digest
    owner: root
    group: root
    mode: "0644"

- name: Copy kickstart file to server
  copy:
    src: files/kickstart.ks
    dest: /var/lib/cobbler/kickstarts/solvchallenge.ks

- name: Upload a CentOS 6 ISO image
  copy:
    src: iso/CentOS-6.7-x86_64-minimal.iso
    dest: /tmp/CentOS-6.7-x86_64-minimal.iso

- name: Mount image for import
  command: mount -o loop /tmp/CentOS-6.7-x86_64-minimal.iso /mnt

# TODO: sanatize check for errors
- name: Import CentOS 6 image in cobbler
  command: cobbler import --path=/mnt/ --name=CentOS_6.7
  ignore_errors: True

- name: UNMount image 
  command: umount /mnt

# TODO: sanatize check for errors
- name: Add systems to cobbler for automatic installation
  command: "cobbler system add --name={{ item.name }} --profile={{ item.profile }} --mac=08:00:27:BC:43:E2 --ip-address={{ item.ipaddress }} --hostname={{ item.hostname }} --interface {{ item.interface }} --kickstart=/var/lib/cobbler/kickstarts/solvchallenge.ks"
  with_items:
    - "{{ BasicConfig_Cobbler_systems }}"
  when: BasicConfig_Cobbler_systems is defined
  ignore_errors: True

- name: Syncronize services from templates
  command: cobbler sync
