---
# tasks file for BasicConfig_Rsync

- name: Installing Rsync packages
  yum:
    name: "rsync"
    state: installed

- name: Template Rsync configuration
  template:
    src: "rsync.j2"
    dest: "/etc/xinetd.d/rsync"
    owner: root
    group: root
    mode: "0644"

- name: Start service
  service: 
    name: xinetd
    state: restarted
    enabled: yes