---
# tasks file for BasicConfig_Docker

- name: Installing Docker packages
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - docker-io
    - python-pip
  register: docker_install

- name: Install Docker.py via python-pip
  command: pip install docker-py==1.2.2

- name: Start docker daemon service
  service: 
    name: docker
    state: started
    enabled: yes

# Reboot the machine and wait for it to come back online
# Nessecary for kernel update
- name: restart machine
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  sudo: true
  ignore_errors: true
  when: docker_install.changed

- name: waiting for server to come back
  local_action: wait_for host={{ inventory_hostname }} state=started delay=30 timeout=300 port=22
  sudo: false
  when: docker_install.changed