---
- hosts: '{{ target }}'

  roles:
    # Default disable SELinux
    - BasicConfig_Selinux
    # Install iptables firewall
    - BasicConfig_Iptables
    # Update sysctl to disable ipv6
    - BasicConfig_Sysctl
    # Use Yum role to install EPEL repository
    - BasicConfig_Yum
    # Create users
    - BasicConfig_Users
    # Enable users as administrators
    - BasicConfig_Sudo
    # Configure ssh daemon for use with administrator users
    - BasicConfig_Sshd
    # Install cobbler service
    - BasicConfig_Cobbler
    # Configure tftp service
    - BasicConfig_Tftp
    # Install rsync service
    - BasicConfig_Rsync
